spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/MarlonDaSilvaMartins/ConfigServerRepo
server:
  port: 8888
  servlet:
    context-path: /config-server
